### ISSUE TITLE
Heatmap/Access entry point 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS#105]
By working on this issue https://github.com/CityScope/CS_Simulation_GAMA/issues/138 I realize that when we speak about heatmap we refer to accessibility. This is a great feature and we should keep it, however I think we should also think about another structure (or refactoring and renaming the access one) for other kind of heatmap.

Just as en example imagine if we want to send for instance a temperature heatmap (or a people presence, traffic jam, etc) , then we won't want to label it as an accessibility heatmap .

So we should be able to customize the information (legend, mean, max, actually even color can be great). I think all of that can be embedded in the information sent if we change it a bit. 

No rush just anticipating

**Comment by RELNO** [comment]
@yzheng1998 and I are already working in this direction (see https://github.com/CityScope/CS_cityscopeJS/pull/102). It is doable of course, but there are a few limitations, since we must make sure the data fits the rendering we want (heatmap, lines, pnts, trips etc..) 

In the end, we will get closer to kepler.gl approach, which is quite agnostic to data format. But it's a long way ;)
