### ISSUE TITLE
Inconsistency between type definition in different table

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS#107]
Something related to the way type are created/Stored is different in this table
https://cityio.media.mit.edu/api/table/team-1/
vs this one
https://cityio.media.mit.edu/api/table/dungeonmaster/

This imply this issue https://github.com/CityScope/CS_Simulation_GAMA/issues/155

**Comment by agrignard** [comment]
According to https://github.com/CityScope/CS_Simulation_GAMA/issues/155 there is now a label ```name``` in properties of the GEOGRIDDATA,  it would make more sense to call it ```type ```no? 

In anycase this modification implies a slight change in the way GAMA handles object which is a bit problematic, if there is a label names it will create an instance of this name for now and not an instance of brix of type name.

**Comment by RELNO** [comment]
I can't recall when the decision to call it `name` was made -- I'm ok with both, but this might break things with modules. In a conceptual level, there are no more types anymore, since a type is only the sum of different LBCS/NAICS tags. So for example, the `name` is just how my table will define a `road` but your table would have a different definition to what `road` means

**Comment by agrignard** [comment]
This one has been fixed  CityScope/CS_Simulation_GAMA#155. So it's ok for me. However I am not sure about the meaning of this label ```name``` (for me as it is now it represents more the name of the class or the type) and a name is more something unique like a road name can be Road 66 or Mass Ave, not the name of the class. I let you close this issue if you think it's ok like that
