### ISSUE TITLE
Fix active layer on init 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_cityscopeJS#19]
on menu, layers should be on/off on init via `config.json`.

**Comment by gok03** [comment]
What would be the difference between settings.json which is already present and config.json?
And where should be config.json placed in the file stucture.

**Comment by RELNO** [comment]
That's a typo, should remain settings.json. The issue is that the menu module should init some toggles as on and others as off, but somehow state is not passed well on init.

**Comment by gok03** [comment]
Layers having value as true at settings.menu.toggles works well on app init. The state is updated with the values and layers are getting rendered properly.

**Comment by RELNO** [comment]
> Layers having value as true at settings.menu.toggles works well on app init. The state is updated with the values and layers are getting rendered properly.

after first toggle yes, but there's an issue with `grid` toggle, which is turned off after on any other toggle click first.

**Comment by gok03** [comment]
The problem seems to be at the toggleStateArray.
The initial value while setting state for toggleStateArray seems to be [], where as it should be all the toggled on layers(ex- ["GRID", "TEXT"]).

work around should be -

` const [toggleStateArray, setChecked] = React.useState(
        Object.keys(settings.menu.toggles)
        .filter(function(k){return settings.menu.toggles[k]})
        .map(String)
    );`

instead of -
`const [toggleStateArray, setChecked] = React.useState();`

**Comment by RELNO** [comment]
@gok03 very nice, thanks
