### ISSUE TITLE
Redesign sidebar UI to include layers control 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_cityscopeJS#66]
@yzheng1998 following today's conv., it would be good to consolidate fine-grain layers control (ABM, Access, etc) into the sidebar, similar to https://medium.com/@modularcoder/reactjs-multi-level-sidebar-navigation-menu-with-typescrip-materialui-251943c12dda 

The idea is that instead of the ABM control panel, the sliders will appear when the layer is on. 
Same for Access layer, as mentioned in #65. 

Design wise, we can inherit the style as well.

**Comment by RELNO** [comment]
Great start:
- I'm getting this error on init, probably related to spawning multiple menu items without unique keys   
![Screen Shot 2020-03-31 at 09 19 57](https://user-images.githubusercontent.com/14296774/78030901-ce995080-7330-11ea-85a4-056cd401860d.png)
- access layer is still not parsed ( I assume it's the To Do?) 
- migrate to black theme, similar to the docs mini site

**Comment by doorleyr** [comment]
The list of access layer names have been hardcoded into the FE:
https://github.com/CityScope/CS_cityscopeJS/blob/master/src/components/menu/AccessSubmenu/index.js
This doesn't work because the list of access variables is not always the same. It will be different in different projects and even in the same project can change over time. Even now, the access layers for Corktown are all mixed up (i.e. the 'nightlife' layer is actually the housing layer) because the ordering of the access variables in the geojson changed and the front-end didn't notice. The FE needs to get this list from the properties of the geojson. This can be done just once on start-up.
