### ISSUE TITLE
Improve road network for GB/CT

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_cityscopeJS#8]
Road network should include more node to improve trips layer accuracy and realism: 

<img width="419" alt="Screen Shot 2019-10-25 at 09 08 20" src="https://user-images.githubusercontent.com/14296774/67573783-22ab6380-f707-11e9-81a5-bc6ccc8827cc.png">

**Comment by agrignard** [comment]
What about starting with open street map network?

For Hamburg it looks more detailed that what we have now

https://www.openstreetmap.org/search?query=hamburg#map=17/53.53047/10.01657

**Comment by doorleyr** [comment]
The networks are already from OpenStreetMap. I've looked into this and the problem is not with the networks. If you look at both the GAMA visualisation and the javascript visualisation, you see that in GAMA, the agents follow the road network but in the JS visualisation, they cut a lot of corners. In the two images below, look at the agents arriving at the site and heading towards the interactive area. This is because the agent positions are sampled at a constant time interval to be sent to cityIO. This means if an agent is sampled before a corner and their next sample is after the corner, then in the JS viz, they will take a straight line between those two points, cutting the corner. 

The problem can be made a bit better just by increasing the sampling rate. However, this will result in a lot of unnecessary sample points when agents are travelling in a straight line and will not still completely solve the problem of corner cutting. The best way is to record the position and timestamp of every node the agent arrives. This will give us the minimal amount of sampling in order to properly recreate the trajectory. @agrignard do you know a good way to do this?

<img width="674" alt="Screenshot 2019-10-28 at 10 42 33" src="https://user-images.githubusercontent.com/7722116/67672824-a916ae00-f970-11e9-8af1-508889dbd3b8.png">

<img width="895" alt="Screenshot 2019-10-28 at 10 45 06" src="https://user-images.githubusercontent.com/7722116/67672835-af0c8f00-f970-11e9-8af4-3a1d8d820e90.png">

**Comment by agrignard** [comment]
@doorleyr did you extract it directly from openstreet map or draw it from openstreet map

For me it seems that there is more "vertex" on openstreet map than what we have now
<img width="1131" alt="Screen Shot 2019-10-28 at 10 15 52" src="https://user-images.githubusercontent.com/3928502/67685839-2855b300-f96c-11e9-852e-bc368e4e6f6e.png">


_The best way is to record the position and timestamp of every node the agent arrives. This will give us the minimal amount of sampling in order to properly recreate the trajectory. @agrignard do you know a good way to do this?_


As you said one way to increase the sample rate is to modify this parameters but this will increase the size of the produced geojson by modifying ````saveLocationInterval````. Then I don't see indeed how to save only if it's an existing node... maybe one solution but I am afraid it will make the simulation very slow is to build a map of the position that match with the network ones and save only if it fits. it might be worth exploring this option)

**Comment by doorleyr** [comment]
I take the road network information directly from OSM but there is some small simplification which converts curved links to straight links. I can change this to not do the simplification but there will be an increase in the number of links. Besides, this only makes a small difference to some trajectories. The larger issue in the JS visualisation is due to the sampling. I created a separate issue about this in the CS_Gama_Simulation repo so we can keep this issue focussed on the road networks.

**Comment by RELNO** [comment]
In Corktown we've observed the sampling issue more clearly, as some agents follow 90deg turns nicely while other cut corners.

**Comment by agrignard** [comment]
Again we can increase the sampling (the sampling is not a restriction of GAMA but a restriction of the cityIO/backend design as we don't want to store hundreds of Mb for one table).

So anyway the network need to be also more precise (with a compromise between detail and size). @doorleyr can we check with the none simplify one to see how it look (maybe by differentiated them with 2 different name for now?

**Comment by agrignard** [comment]
@doorleyr what is your process to extract the road network? Are you taking directly from openstreet map our using an intermediate script? I'd like to test with different qualities of network? Can you point me to the doc/code to extract the network and have it compatible with our tools?

**Comment by doorleyr** [comment]
I was using a library called [osmnet](https://github.com/UDST/osmnet) which as discussed above was converting some curved links into single straight links for higher efficiency in path-finding. However, since this was affecting the visualisation, I've now updated the code to use the OSM network data exactly.
eg: https://github.com/CityScope/CS_Mobility_Service/blob/master/scripts/cities/Hamburg/clean/driving_net.geojson

The python code is here: https://github.com/CityScope/CS_Mobility_Service/blob/master/scripts/get_osm_network.ipynb

**Comment by doorleyr** [comment]
@agrignard Can you also try the following geojsons:

https://github.com/CityScope/CS_Mobility_Service/blob/master/scripts/cities/Detroit/clean/driving_net_simple.geojson
https://github.com/CityScope/CS_Mobility_Service/blob/master/scripts/cities/Detroit/clean/pt_net_simple.geojson
etc.

These geojsons have MultiLine features. The previous ones had a feature for every road segment. These should be more efficient I think.

These ones were created with this python code:
http://localhost:8888/notebooks/Google%20Drive%20File%20Stream/My%20Drive/Media%20Lab/NuevoScope/CS_Mobility_Service/scripts/overpass_to_geojson.ipynb

**Comment by agrignard** [comment]
Great! much more better!

**Comment by agrignard** [comment]
However to see it properly in deckgl i need to send a lot of points.

**Comment by agrignard** [comment]
<img width="1281" alt="Screen Shot 2019-11-05 at 17 24 21" src="https://user-images.githubusercontent.com/3928502/68251456-28e7ec80-fff1-11e9-9daf-1522ae0ebaba.png">

**Comment by RELNO** [comment]
done with latest gama update
